name: eyeglaze
description: "EyeGlaze - Premium Eyewear Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  http_parser: ^4.0.2
  image_picker: ^1.0.8
  shared_preferences: ^2.2.0
  provider: ^6.1.0
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  flutter_secure_storage: ^9.0.0
  socket_io_client: ^3.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
